export const EVENTS = {
    // Guard events
    GUARD_CONNECT: 'GUARD_CONNECT',
    GUARD_LOCATION: 'GUARD_LOCATION',
    GUARD_STATUS: 'GUARD_STATUS',
    GUARD_CHECKIN: 'GUARD_CHECKIN',
    GUARD_CHECKOUT: 'GUARD_CHECKOUT',
    
    // Supervisor events
    SUPERVISOR_CONNECT: 'SUPERVISOR_CONNECT',
    ASSIGN_DUTY: 'ASSIGN_DUTY',
    
    // Alert events
    INCIDENT_REPORT: 'INCIDENT_REPORT',
    GEOFENCE_BREACH: 'GEOFENCE_BREACH',
    ATTENDANCE_ALERT: 'ATTENDANCE_ALERT',
    
    // System events
    JOIN_ZONE: 'JOIN_ZONE',
    LEAVE_ZONE: 'LEAVE_ZONE'
  };